### PR TITLE
complete junk project - be honest about intentions

### PR DESCRIPTION
**Pull request by dimyme**
everyone is advised to immediatley delete this bloatware !

### CODE REVIEW

**Comment by dimyme** [comment]
:-1:  :camel: :hankey: :nauseated_face:

**Comment by dimyme** [comment]
already the preload of firefox from /usr/...../autostart  was a huge mess.

what are you doing ?  :-1:

**Comment by star-buck** [comment]
You mad? (_shrug_)

**Comment by NuLogicSystems** [comment]
Due to the sandboxing of autoconfig by mozilla, cck2 would no longer function, so a move to using the built in enterprise policies was needed. I however didn't notice that a change from using pref to defaultPref was also required. These issues should now be fixed with this commit: https://github.com/netrunner-rolling/netrunner-settings-firefox/commit/9153f8366aedac585dc483e242bcc138aacb991d

@dimyme 
I apologize if this caused you any issues. I'll be looking into removing the preload like we did for the Debian edition as well. However, that setting is in a different package.

**Pull request closed without merging**
